# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files into the container at /app
COPY frontend/package.json ./

# Install the project dependencies
RUN npm install

# Copy the rest of your application code into the container at /app
COPY /frontend /app

# Build your React application (adjust the build command if needed)
RUN npm run build

# Expose the port your React app will run on (e.g., 3000)
EXPOSE 5300

# Define the command to start your React app
CMD ["npm", "start"]
