# Use an official Python runtime as a parent image
FROM python:3.8
RUN apt-get update && apt-get install -y libgl1-mesa-glx
# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file into the container at /app
COPY backend/requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application code into the container at /app
COPY /backend /app/

# Expose port 4242 (or the port your FastAPI application is running on)
EXPOSE 4242

# Define the command to run your FastAPI application using Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "4242"]
